variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  variables:
    DOCKER_COMPOSE_OVERRIDE: $DOCKER_COMPOSE_OVERRIDE
  script:
    - pwd
    - cp "$DOCKER_COMPOSE_OVERRIDE" docker-compose.override.yml
    - docker-compose up --build -d
