version: "3.9"
services:
  web:
    restart: always
    build: .
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=file:/app/tmp/db.sqlite
      - PYTHON3_PATH=/usr/bin/python3
      - SQLITE3_PATH=/usr/bin/sqlite3
    volumes:
      - tmp:/app/tmp
      - dataset:/app/dataset

volumes:
  tmp:
  dataset:
