/* eslint-disable @next/next/no-img-element */
import { css, Global } from "@emotion/react"
import { Button, Divider, FileInput, Text, Title } from "@mantine/core"
import { type NextPage } from "next"
import Head from "next/head"

import { trpc } from "../utils/trpc"

const AudioMatch = (props: { image: string; name: string; author: string }) => {
  return (
    <div
      css={css`
        display: grid;
        grid-template-columns: auto 1fr;
        align-items: center;
        gap: 12px;
      `}
    >
      <img src={props.image} alt={props.name} css={{ borderRadius: 4 }} />
      <div>
        <Text css={{ fontWeight: 700, lineHeight: "1.2em" }}>{props.name}</Text>
        <Text>{props.author}</Text>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" })

  return (
    <>
      <Head>
        <title>VMM Audio Matching</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Global
        styles={css`
          *,
          *:before,
          *:after {
            box-sizing: border-box;
          }

          body {
            margin: 0;
            padding: 0;
          }
        `}
      />
      <main
        css={css`
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          background: #1f2937;

          min-height: 100vh;
        `}
      >
        <div
          css={css`
            display: flex;
            flex-direction: column;
            gap: 16px;

            width: 100%;
            max-width: 420px;
          `}
        >
          <Title
            order={2}
            css={css`
              color: white;
              text-align: center;
            `}
          >
            NI-VMM Audio Podobnost
          </Title>
          <div
            css={css`
              background: white;
              padding: 16px;
              padding-top: 14px;
              border-radius: 12px;

              width: 100%;

              box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.2);

              display: flex;
              flex-direction: column;
              gap: 8px;
            `}
          >
            <Text>Nahrát audio nahrávku</Text>
            <form
              css={css`
                display: grid;
                gap: 12px;
                grid-template-columns: minmax(200px, 1fr) auto;
              `}
            >
              <FileInput />
              <Button>Nahrát</Button>
            </form>
          </div>

          <div
            css={css`
              background: white;
              padding: 16px;
              border-radius: 12px;
              width: 100%;

              display: flex;
              flex-direction: column;
              gap: 12px;
            `}
          >
            <AudioMatch
              image="https://picsum.photos/64/64"
              author="Apache"
              name="Witches"
            />

            <Divider />

            <AudioMatch
              image="https://picsum.photos/64/64"
              author="Apache"
              name="Witches"
            />

            <Divider />

            <AudioMatch
              image="https://picsum.photos/64/64"
              author="Apache"
              name="Witches"
            />

            <Divider />

            <AudioMatch
              image="https://picsum.photos/64/64"
              author="Apache"
              name="Witches"
            />
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
